import { test, expect } from "@playwright/test";
test("actual App Faculty catalogue, details, create/edit/reload and no publication shortcut", async ({ page }, info) => {
  await page.goto("/expo");
  await page.getByRole("link", { name: "Faculty demo — case management" }).click();
  await expect(page.getByRole("heading", { name: "Available cases" })).toBeVisible();
  await expect(page.getByText("APPROVED_EXPO", { exact: true })).toHaveCount(2);
  await expect(page.getByRole("link",{name:"Dana / Anaphylaxis",exact:true})).toBeVisible();
  await page.screenshot({ path: info.outputPath("faculty-catalogue.png"), fullPage: true });
  await page.getByRole("link", { name: "Khalid / STEMI",exact:true }).click();
  await expect(page.getByText(/Publication lifecycle: UNDER_REVIEW/)).toBeVisible();
  await expect(page.getByText(/Physician identity and exact review timestamp: Not formally recorded/)).toBeVisible();
  await expect(page.getByText(/legacy 84-bpm ECG is not reintroduced/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Save DRAFT" })).toHaveCount(0);
  await page.screenshot({ path: info.outputPath("faculty-stemi-details.png"), fullPage: true });
  await page.getByRole("link", { name: "New Case Draft" }).click();
  await page.getByLabel("Title", { exact: true }).fill("Expo learning draft");
  await page.getByLabel("Short educational description").fill("Metadata demonstration — no authored medical truth.");
  await page.screenshot({ path: info.outputPath("faculty-new-draft.png"), fullPage: true });
  await page.getByRole("button", { name: "Save DRAFT" }).click();
  await expect(page.getByText("DRAFT", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Expo learning draft", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "Expo learning draft", exact: true })).toBeVisible();
  await page.getByLabel("Title", { exact: true }).fill("Edited Expo draft");
  await page.getByRole("button", { name: "Save DRAFT" }).click();
  await expect(page.getByText(/metadata revision 1/)).toBeVisible();
  await page.screenshot({ path: info.outputPath("faculty-created-draft.png"), fullPage: true });
  await page.reload(); await expect(page.getByRole("heading", { name: "Edited Expo draft", exact: true })).toBeVisible();
  const headers = { Origin: "http://127.0.0.1:4193" };
  const injected = await page.request.post("/__faculty/cases", { headers, data: { title: "Bad", status: "PUBLISHED" } });
  expect(injected.status()).toBe(400);
  expect((await page.request.post("/__faculty/publish", { headers, data: {} })).status()).toBe(404);
  expect((await page.request.post("/__faculty/review", { headers, data: {} })).status()).toBe(404);
  expect((await page.request.post("/__faculty/cases", { headers: { Origin: "https://untrusted.invalid" }, data: {} })).status()).toBe(403);
  await page.getByRole("link", { name: "Case catalogue", exact: true }).click();
  await expect(page.getByRole("link", { name: "Edited Expo draft" })).toBeVisible();
});
