import {useRef,useState} from 'react';
import type {QuickOrderPlan,PatientLanguage,SafeLearnerAction,JsonObject} from '@ai-clinical-simulation/contracts';
import type {StudentUiServices} from '../../app/types';
import {Button} from '../../components/ui';
import {learnerActionLabel} from './action-model';
export function QuickOrderPanel({service,sessionId,locale,actions,enabled,refresh,onChoose}:{service:NonNullable<StudentUiServices['quick_orders']>;sessionId:string;locale:PatientLanguage;actions:readonly SafeLearnerAction[];enabled:boolean;refresh():Promise<unknown>;onChoose(action:SafeLearnerAction,parameters:JsonObject):void}){
 const [text,setText]=useState(''),[plan,setPlan]=useState<QuickOrderPlan>(),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const pending=useRef(false),ar=locale==='ar-JO';
 async function resolve(){if(pending.current||!enabled)return;pending.current=true;setBusy(true);setMessage('');setPlan(undefined);try{const p=await service.plan(sessionId,text,locale);setPlan(p);setMessage(p?'':ar?'تعذر تفسير الطلب. استخدم القائمة.':'Order interpretation unavailable; use the catalogue.');}catch{setMessage(ar?'تعذر تفسير الطلب. استخدم القائمة.':'Order interpretation unavailable; use the catalogue.');}finally{pending.current=false;setBusy(false);}}
 async function confirm(){if(!plan||pending.current||!enabled)return;pending.current=true;setBusy(true);try{
  const indexes=plan.fragments.flatMap((f,i)=>f.interpretation.status==='MATCH'&&!f.interpretation.candidate.unresolved_required_parameters.length?[i]:[]);
  const r=await service.confirm(sessionId,plan.plan_id,indexes);setMessage(!r?(ar?'تعذر تأكيد التنفيذ. راجع سجل النشاط قبل المحاولة.':'Execution could not be confirmed. Review activity before retrying.'):r.stopped?(ar?'توقف التنفيذ. راجع المتطلبات والإجراءات المسجلة.':'Execution stopped. Review prerequisites and recorded actions.'):(ar?'تم تسجيل الإجراءات المؤكدة.':'Confirmed actions recorded.'));if(r)setPlan(undefined);await refresh();
 }catch{setMessage(ar?'تعذر تأكيد التنفيذ. راجع سجل النشاط قبل المحاولة.':'Execution could not be confirmed. Review activity before retrying.');}finally{pending.current=false;setBusy(false);}}
 return <section aria-label="Quick clinical order"><h3>{ar?'طلب سريري سريع':'Quick clinical order'}</h3><p>{ar?'راجع كل طلب ثابت وجرعته قبل التأكيد. الأجزاء غير المحلولة لن تنفذ.':'Review every fixed order and dose before confirming. Unresolved fragments will not execute.'}</p>
 <label>{ar?'نص الطلب':'Order text'}<textarea value={text} maxLength={4000} disabled={!enabled||busy} onChange={e=>{setText(e.target.value);setPlan(undefined);}}/></label>
 <Button disabled={!enabled||busy||!text.trim()} onClick={()=>void resolve()}>{ar?'تفسير الطلبات':'Interpret orders'}</Button>
 {plan?<><ol>{plan.fragments.map((f,i)=>{const interpretation=f.interpretation;const action=interpretation.status==='MATCH'?actions.find(a=>a.action_id===interpretation.candidate.action_id):undefined;const candidates=interpretation.status==='AMBIGUOUS'?interpretation.candidates:interpretation.status==='MATCH'&&interpretation.candidate.unresolved_required_parameters.length?[interpretation.candidate]:[];return <li key={i}><span>{f.text}</span> — {action?<strong>{learnerActionLabel(action,locale)}</strong>:<span>{ar?'يحتاج توضيحاً؛ اختر من القائمة':'Needs clarification; select from the catalogue'}</span>}{candidates.length?<div><p>{ar?'اختر طلباً وراجع معطياته في النموذج اليدوي. لن يُنفّذ هذا الجزء تلقائياً.':'Choose an order and review its parameters in the manual form. This fragment will not execute automatically.'}</p>{candidates.map(c=>{const a=actions.find(x=>x.action_id===c.action_id);return a?<Button key={c.action_id} disabled={!enabled||busy} onClick={()=>onChoose(a,c.parameters)}>{learnerActionLabel(a,locale)}</Button>:null;})}</div>:null}</li>;})}</ol>
 <Button disabled={!enabled||busy||!plan.fragments.some(f=>f.interpretation.status==='MATCH'&&!f.interpretation.candidate.unresolved_required_parameters.length)} onClick={()=>void confirm()}>{ar?'تأكيد وتنفيذ الطلبات المحلولة فقط':'Confirm and execute resolved orders only'}</Button></>:null}<p role="status">{message}</p></section>;
}
