import { SafeLearnerActionCatalogueSchema } from "../../../packages/contracts/src/index.ts";

export const EXPO_CATALOGUE_IDENTITY = {
  catalogue_id: "catalogue.balsim.expo-clinical",
  version: "1.0.0",
} as const;
// Public vocabulary ONLY. No Case truth, scores, correctness, effects or bindings.
const rows = [
  [
    "bp",
    "EXAMINATION",
    "OBSERVATIONS",
    "Vitals",
    "Measure blood pressure",
    "قياس ضغط الدم",
    "blood pressure|BP",
    "ضغط الدم",
  ],
  [
    "pulse",
    "EXAMINATION",
    "OBSERVATIONS",
    "Vitals",
    "Assess pulse",
    "قياس النبض",
    "pulse|heart rate",
    "نبض",
  ],
  [
    "pulse-ox",
    "EXAMINATION",
    "OBSERVATIONS",
    "Vitals",
    "Pulse oximetry — SpO2 and pulse",
    "قياس SpO2 والنبض",
    "pulse oximetry|SpO2",
    "إشباع الأكسجين",
  ],
  [
    "respirations",
    "EXAMINATION",
    "OBSERVATIONS",
    "Vitals",
    "Assess respiratory rate",
    "قياس معدل التنفس",
    "respiratory rate|RR",
    "معدل التنفس",
  ],
  [
    "temperature",
    "EXAMINATION",
    "OBSERVATIONS",
    "Vitals",
    "Measure temperature",
    "قياس الحرارة",
    "temperature",
    "حرارة",
  ],
  [
    "ecg",
    "INVESTIGATION",
    "INVESTIGATIONS",
    "Cardiology",
    "12-lead ECG",
    "تخطيط القلب ECG",
    "ECG|electrocardiogram|12-lead ECG",
    "تخطيط القلب",
  ],
  [
    "cxr",
    "INVESTIGATION",
    "INVESTIGATIONS",
    "Imaging",
    "Chest X-ray",
    "أشعة الصدر",
    "CXR|chest radiograph",
    "صورة الصدر",
  ],
  [
    "aspirin",
    "MEDICATION",
    "MEDICATIONS",
    "Fixed orders",
    "Aspirin 324 mg — chewed",
    "أسبرين 324 ملغ — مضغ",
    "aspirin|ASA",
    "أسبرين",
  ],
  [
    "ticagrelor",
    "MEDICATION",
    "MEDICATIONS",
    "Fixed orders",
    "Ticagrelor 180 mg — oral",
    "تيكاغريلور 180 ملغ — فموي",
    "ticagrelor",
    "تيكاغريلور",
  ],
  [
    "clopidogrel",
    "MEDICATION",
    "MEDICATIONS",
    "Fixed orders",
    "Clopidogrel 600 mg — oral",
    "كلوبيدوغريل 600 ملغ — فموي",
    "clopidogrel",
    "كلوبيدوغريل",
  ],
  [
    "ufh",
    "MEDICATION",
    "MEDICATIONS",
    "Fixed orders",
    "Unfractionated heparin 70 units/kg — IV bolus",
    "هيبارين غير مجزأ 70 وحدة/كغ — دفعة IV",
    "unfractionated heparin|UFH",
    "هيبارين",
  ],
  [
    "atorvastatin",
    "MEDICATION",
    "MEDICATIONS",
    "Fixed orders",
    "Atorvastatin 80 mg — oral",
    "أتورفاستاتين 80 ملغ — فموي",
    "atorvastatin",
    "أتورفاستاتين",
  ],
  [
    "epinephrine",
    "MEDICATION",
    "MEDICATIONS",
    "Fixed orders",
    "Adrenaline (epinephrine) 0.5 mg — IM anterolateral thigh",
    "أدرينالين 0.5 ملغ — عضلي بالجانب الأمامي الوحشي للفخذ",
    "adrenaline|epinephrine",
    "أدرينالين|إبينفرين",
  ],
  [
    "repeat-epinephrine",
    "MEDICATION",
    "MEDICATIONS",
    "Fixed orders",
    "Repeat adrenaline 0.5 mg — IM anterolateral thigh",
    "تكرار أدرينالين 0.5 ملغ — عضلي بالجانب الأمامي الوحشي للفخذ",
    "repeat adrenaline|repeat epinephrine",
    "تكرار الأدرينالين",
  ],
  [
    "iv",
    "PROCEDURE",
    "PROCEDURES",
    "Access",
    "Establish peripheral IV access",
    "تركيب مدخل وريدي IV",
    "IV access|cannula|IV cannula",
    "خط وريدي|كانيولا",
  ],
  [
    "saline-250",
    "PROCEDURE",
    "PROCEDURES",
    "Fluids",
    "Normal saline 250 mL — IV challenge over 10 clinical minutes",
    "محلول ملحي 250 مل — IV خلال 10 دقائق سريرية",
    "saline 250|normal saline challenge",
    "محلول ملحي 250",
  ],
  [
    "crystalloid-500",
    "PROCEDURE",
    "PROCEDURES",
    "Fluids",
    "Crystalloid 500 mL — IV bolus",
    "محلول بلوراني 500 مل — دفعة IV",
    "crystalloid 500|fluid bolus 500",
    "بلوراني 500",
  ],
  [
    "oxygen",
    "PROCEDURE",
    "SUPPORTIVE_CARE",
    "Respiratory support",
    "Supplemental oxygen",
    "أكسجين إضافي",
    "oxygen|O2",
    "أكسجين",
  ],
  [
    "monitor",
    "PROCEDURE",
    "MONITORING",
    "Monitoring",
    "Apply bedside monitoring",
    "توصيل المراقبة السريرية",
    "bedside monitor|monitoring",
    "مراقبة",
  ],
  [
    "help",
    "CONSULT",
    "SUPPORTIVE_CARE",
    "Escalation",
    "Call resuscitation team",
    "طلب فريق الإنعاش",
    "call for help|resuscitation team",
    "طلب المساعدة",
  ],
  [
    "cath",
    "CONSULT",
    "SUPPORTIVE_CARE",
    "Escalation",
    "Activate Cath Lab / primary PCI pathway",
    "تفعيل مسار مختبر القسطرة PCI",
    "cath lab|primary PCI",
    "مختبر القسطرة",
  ],
] as const;
export const EXPO_SHARED_CATALOGUE = SafeLearnerActionCatalogueSchema.parse({
  catalogue_schema_version: "1.0",
  identity: EXPO_CATALOGUE_IDENTITY,
  actions: rows.map((
    [id, action_type, category, subcategory, en, ar, enAliases, arAliases],
  ) => ({
    action_id: `concept.expo.${id}`,
    action_type,
    category,
    subcategory,
    labels: [{ locale: "en-US", label: en }, { locale: "ar-JO", label: ar }],
    aliases: [{ locale: "en-US", phrases: enAliases.split("|") }, {
      locale: "ar-JO",
      phrases: arAliases.split("|"),
    }],
    parameter_definitions: [],
    confirmation_policy: "NONE",
    repeat_policy: category === "OBSERVATIONS"
      ? "REPEATABLE"
      : "NOT_REPEATABLE",
    prerequisite_concept_ids:
      ["ufh", "saline-250", "crystalloid-500"].includes(id)
        ? ["concept.expo.iv"]
        : id === "repeat-epinephrine"
        ? ["concept.expo.epinephrine"]
        : [],
  })).sort((a, b) =>
    a.action_id < b.action_id ? -1 : a.action_id > b.action_id ? 1 : 0
  ),
});
